### ISSUE TITLE
Partials don't include headers that was defined in macro

### ISSUE THREAD

**Issue by artemEmbSw** [ThrowTheSwitch/Ceedling#1267]
Hello!

In addition to this [problem](https://github.com/ThrowTheSwitch/Ceedling/issues/1223) I noticed that partials don't include headers that are defined in macro:

Modified AlertManager.c:
```
#include "Types.h"
#include "AlertManager.h"

#define STR(x)                   #x
#define INCLUDE_DEVICE(dev)      STR(dev.h)

#if SOIL_MOISTURE_MAX > 0
#   include INCLUDE_DEVICE(types2)
#endif

#include "UartDriver.h"

#define TEMP_HIGH_THRESHOLD_MC  (40000)
#define TEMP_LOW_THRESHOLD_MC   (-10000)
#define HUMIDITY_HIGH_THRESHOLD (90u)
#define HUMIDITY_LOW_THRESHOLD  (10u)
#define SOIL_DRY_THRESHOLD      (20u)

static AlertEntry_t s_alert_table[ALERT_MANAGER_MAX_ALERTS];
static uint8        s_alert_count;

static int8 AlertManager__FindFreeSlot(void)
{
    uint8 i = SOME_VALUE;

    for (i = 0u; i < ALERT_MANAGER_MAX_ALERTS; i++)
    {
        if (!s_alert_table[i].active) { return (int8)i; }
    }
    return -1;
}
```
Still I get the same issue with no found macros. Ran the build:
```
👟 Building Objects
-------------------
Compiling TestAlertManager.c...
Compiling TestAlertManager::AlertManager.c...
Compiling TestAlertManager::unity.c...
Compiling TestAlertManager::cmock.c...
Compiling TestAlertManager::ceedling_partial_AlertManager_impl.c...
Compiling TestAlertManager::TestAlertManager_runner.c...
Compiling TestAlertManager::MockUartDriver.c...
🧨 EXCEPTION: 'Default Test Compiler' (gcc) terminated with exit code [1] and output ⏩️
src/AlertManager.c: In function ‘AlertManager__FindFreeSlot’:
src/AlertManager.c:31:15: error: ‘SOME_VALUE’ undeclared (first use in this function)
   31 |     uint8 i = SOME_VALUE;
      |               ^~~~~~~~~~
src/AlertManager.c:31:15: note: each undeclared identifier is reported only once for each function it appears in
Executed Command: gcc -std=c99 -I"build/test/mocks/TestAlertManager" -I"build/test/partials/TestAlertManager" -I"src" -I"build/vendor/unity/src" -I"build/vendor/cmock/src" -I"build/vendor/ceedling" -D"TEST" -D"CEEDLING_PARTIALS_PREFIX=ceedling_partial_" -D"CMOCK_MOCK_PREFIX=Mock" -D"UNITY_USE_COMMAND_LINE_ARGS" -DGNU_COMPILER -g -c "build/test/partials/TestAlertManager/ceedling_partial_AlertManager_impl.c" -o "build/test/out/TestAlertManager/ceedling_partial_AlertManager_impl.o" -MMD -MF "build/test/dependencies/TestAlertManager/ceedling_partial_AlertManager_impl.d"
🌱 Ceedling could not complete operations because of errors
```

In generated ceedling_partial_AlertManager_impl.c this include header is ignored:
```
// Ceeding generated file
#include "Types.h"
#include "UartDriver.h"
#include "ceedling_partial_AlertManager_impl.h"

AlertEntry_t s_alert_table[ALERT_MANAGER_MAX_ALERTS];
uint8 s_alert_count;

#line 29 "src/AlertManager.c"
int8 AlertManager__FindFreeSlot(void)
{
    uint8 i = SOME_VALUE;

    for (i = 0u; i < ALERT_MANAGER_MAX_ALERTS; i++)
    {
        if (!s_alert_table[i].active) { return (int8)i; }
    }
    return -1;
}
```

Thanks in advance

**Comment by mkarlesky** [comment]
@artemEmbSw I've run some experiments with code using the snippets you've provided. Everything is working fine that I'm able to exercise. `#include "types2.h"` is processed as desired and compilation succeeds. So, either there's something in your project configuration or code behaving differently than you expect, or Ceedling has a bug outside of what I can reproduce with what you've provided. Could you provide a minimal reproducible project to investigate this further?

**Comment by artemEmbSw** [comment]
Sure, here is an example project wondrous_forest. I've changed it to reproduce the behavior. It is built.
[wondrous_forest_changed.zip](https://github.com/user-attachments/files/32049572/wondrous_forest_changed.zip)
I run tests by the command
`ceedling test:AlertManager`

PS. Noticed also, that in case if I want to comment include by using #if 0, then generated partial includes it:
  
```
// Works
#if 0
#if SOIL_MOISTURE_MAX > 0
#include "types2.h"
#endif
#endif
```

**Comment by mkarlesky** [comment]
@artemEmbSw Now we're cooking. I can reproduce the problem. Thank you. The fundamental issue is that C is hard and has lots of crazy quirks. Computed include directives are one of those oddball C things, and these have not been fully supported in the core include directive extraction that Ceedling does irrespective of Partials. This is not a bug exactly but an undocumented known issue. After now digging into this, I've realized that we've made so much progress in our include extractions and preprocessing that I think we can close the remaining gap here. Shooting to now get that change into 1.1.8 and 1.2.0-pre.6.

As for the `#if 0` ending up in the generated Partial itself, that is intentional even if it seems unnecessary. The only way Partials can work is by carefully parsing and lexing your source C files. This required writing custom C extraction from scratch (no fully cross-platform tool exists that can do this and do it for all variations of C). Ceedling's approach is to treat this extraction as specialized text handling, not code handling. That is, the C extraction does not understand what it's extracting and performs no preprocessing of its own. Because preprocessing is so complicated, we leave that to the actual C preprocessor and focus on rearrange source code to create Partials. One of the quirks of this is transplanting entire conditional preprocessor blocks like `#if 0 ... #endif`. It's quirky, but if everything else is working correctly, it's harmless.

**Comment by artemEmbSw** [comment]
Thanks for the response. I'm looking forward for this feature.

**Comment by mkarlesky** [comment]
@artemEmbSw This gap has now been closed, but it proved too much work and too disruptive to add it in 1.1.8. Various under-the-hood changes in 1.2.0 (still prerelease) made the work more sensible there. The nature of it as new functionality also makes it more appropriate for the next minor version instead of a patch release. 1.1.8 will be published shortly without this gap filled. A bit more work on related issues will happen in 1.2.0 before 1.2.0-pre.6 is published with the changes to fill this gap you've identified.

**Comment by mkarlesky** [comment]
@artemEmbSw 1.2.0-pre.6 is now available. Hopefully, it resolves this issue (it does with your repro project and in the expanded test suite).

**Comment by artemEmbSw** [comment]
Hello. I just tested  1.2.0-pre.6 with my project. It works now with the issue. Thanks a lot.

But It looks like I've found another issues. 

1) Check the project please. I added #include "AlertManager.h" to types2.h. And I got redefinition of defined in header structure type. Is it expected?
[wondrous_forest_inc_issue.zip](https://github.com/user-attachments/files/32251826/wondrous_forest_inc_issue.zip)
```
🧨 EXCEPTION: 'Default Test Compiler' (gcc) terminated with exit code [1] and output ⏩️
In file included from build/test/partials/TestAlertManager/ceedling_partial_AlertManager_impl.h:7,
                 from test/TestAlertManager.c:19:
build/test/partials/TestAlertManager/ceedling_partial_AlertManager_types.h:11:3: error: conflicting types for ‘AlertEntry_t’; have ‘struct <anonymous>’
   11 | } AlertEntry_t;
      |   ^~~~~~~~~~~~
In file included from build/test/out/TestAlertManager/d20260915-563994-cjq0h2/types2.h:11,
                 from build/test/partials/TestAlertManager/ceedling_partial_AlertManager_impl.h:6,
                 from test/TestAlertManager.c:19:
src/AlertManager.h:20:3: note: previous declaration of ‘AlertEntry_t’ with type ‘AlertEntry_t’
   20 | } AlertEntry_t;
      |   ^~~~~~~~~~~~
Executed Command: gcc -std=c
```
I can give real example: In my project I have module CAN (can.h, can.c), that sends/receives CAN messages. Also in this module I have can_irq.c, can_irq.h, that handle irq logic and in this module I use types from can.h (e.g. typedef enum for bus number or typedef for callback function)

2) I really like using macro) So, another edge case:
I added this to AlertManager.c
```
void MODULE_CommonTrigCb(void)
{
    // do nothing
}

#define MODULE_DEV_TYPE_CB(dev_type)      \
    void MODULE_TrigCbDev##dev_type(void) \
    {                                     \
        MODULE_CommonTrigCb();            \
    }


MODULE_DEV_TYPE_CB(0)
```

in ceedling_partial_AlertManager_impl.h I got the macro with extra space before ##
`#define MODULE_DEV_TYPE_CB(dev_type) void MODULE_TrigCbDev ##dev_type(void) { MODULE_CommonTrigCb(); }`

Project is here: [wondrous_forest_complex_macro.zip](https://github.com/user-attachments/files/32252439/wondrous_forest_complex_macro.zip)

Thanks in advance.
 
PS. should I create new issues for these?

**Comment by mkarlesky** [comment]
@artemEmbSw Thank you for these reports and even more importantly the reproducible projects! Sorry for the continued trouble. You're pushing into the edge cases of new features and finding issues (which is very good but I'm sure a little disappointing).

Yes, please open these as two new issues. Particularly the macro declaration that is a function definition is very likely tripping up the custom C extraction. I'm quite sure we do not have a test case for that condition!
