### ISSUE TITLE
Testing registers doesn't work on Ceedling v1.0, but works on v0.3

### ISSUE THREAD

**Issue by mundodisco8** [ThrowTheSwitch/Ceedling#955]
Hi,

I'm trying to replicate Mark's article about [testable registers](http://vandervoord.net/blog/2015/5/24/unit-test-how-registers).

I've been fighting it for a while in a project that I retook recently, and I couldn't figure out how to make it work. Then I realised that I am currently using the daily release, while the last time I touched the project, I was suing the 0.3 gem. So I did a quick test with the simplest code I could think of, and it runs on v0.3

```
Compiling cmock.c...
Linking test_a.out...
Running test_a.out...

--------------------
OVERALL TEST SUMMARY
--------------------

No tests executed.
```

While it complains about multiple definitions on v1.0.

```
👟 Building Test Executables
----------------------------
Linking test_a.out...
🧨 EXCEPTION: 'Default Test Linker' (gcc) terminated with exit code [1] and output >>
/usr/bin/ld: build/test/out/test_a/test_a_runner.o:/mnt/c/Users/mundo/OneDrive/Desktop/New folder/test/test/support/bgm220pc22wga.h:22: multiple definition of `TIMER0'; build/test/out/test_a/test_a.o:/mnt/c/Users/mundo/OneDrive/Desktop/New folder/test/test/support/bgm220pc22wga.h:22: first defined here
collect2: error: ld returned 1 exit status
🌱 Ceedling could not complete operations because of errors
```

I prepared a zip file with the smallest file I could think of:

```c
// a.h
void foo(void);
```

```c
//a.c
#include "a.h"
#include "em_timer.h"

void foo(void) {
    TIMER0->EN_SET = TIMER_EN_EN;
}
```

And then I have  a bunch of fake files in test/support with all the files I need to get the correct definitions for the timer register (I understand I don't need to replicate the exact list of includes, that I could have included all the needed stuff in one single file, but I was trying different things to see if I could make it work). I attach the zip so you can test yourselves. The test folder has two project.yml, one for ceedling v0.3 and one for ceedling v1.0.

Does something have changed in the latest version that makes this approach invalid? Am I doing something silly in my project.yml?

[testableRegisters.zip](https://github.com/user-attachments/files/17814383/testableRegisters.zip)

**Comment by deltalejo** [comment]
It seems that when macro `TEST` is defined, the macro `EXTERN` is defined without value, so in file `test/test/support/bgm220pc22wga.h` identifier `TIMER0` ends up being a definition and not a declaration, so every source file that directly or indirectly include that header file will have its own definition of `TIMER0` making the linker complains about multiple definitions.

**Comment by mundodisco8** [comment]
Hey,

Thanks for taking the time to look into my issue. That's correct, and that was the point of the article I link to. The idea is to offer a definition of `TIMER0` with the `EXTERN` keyword to all units, and then play with the meaning of `EXTERN`. The `EXTERN` keyword, as you noted, is preceeded with these macros

```
#ifdef TEST
#   ifndef EXTERN
#       define EXTERN extern
#   endif 
#endif
```

Because TEST is added to my tests (it's in the project.yml), all the test code will hit the `ifndef`, and because `EXTERN` is not pre-defined, `EXTERN` will become `extern`, which will make all the pieces of code that include `TIMER0` compile happily. The linker will complain, though, as there's no definition of `TIMER0` anywhere. We need one and only one copy of `TIMER0` that doesn't have the `extern` keyword.

In my test file, I include `testable_micro_registers.h`, whose only role is to `#define EXTERN`. That way, when I hit the previous macro, `EXTERN` is already defined, so `EXTERN` doesn't become `extern`, but remains empty. This way, one copy of the header has a declaration of `TIMER0` as

```
TIMER_Typedef* TIMER0;
```

I just need to provide a definition for it somewhere and I can test registers.

This works in Ceedling v0.3.2 (I left a `project.yml` for v0.3.2 and you can see how that works). In v1.0, for some reason, this has stopped working. I think the test runner are being generated differently, and now also include all the `#includes` in the test file, so I end up with two declarations of `TIMER_Typedef* TIMER0;` without the `extern` keyword`, so the linker complains about the multiple definitions.

I was wondering if I'm doing something wrong, or if there were changes in v1.0 that prevented this approach to test registers

**Comment by deltalejo** [comment]
Well, I think it should be avoided to put actual definitions on header files. I suggest you to create a source file (.c) with the actual register definitions and add it to the suport files/path on your `project.yml`.

**Comment by mundodisco8** [comment]
I totally agree with you about not having definitions in a header. I understand why is not a standard practice, and I do my best to only include definitions in my c files.

I understand that adding a definition to a header is a bad idea, because then, if the header is included in more than one translation unit, then your linker ends up with multiple definitions. It's ~ok~ valid to do it as long as you can guarantee that your header is only included in one translation unit, but why risk it, right? But the point I'm trying to make here is that I'm adding guards to make sure that there's only ONE definition of the register.

As I said, I'm trying to follow an article that Mark wrote. It's true that the article is almost 10 years old, and it might not be a good practice now (or maybe it wasn't a good practice 10 years ago either), but the fact is that the code I attached works as expected in Ceedling v0.3.2, and not in v1.0, and I'm just wondering if it's because of a bug, or because the way things are in v1.0. I have a bunch of tests that use that technique. I could try to figure out something else, but if I don't have to rewrite those tests, then all the better.

**Comment by deltalejo** [comment]
The include guard will only avoid for the same header file to be included more than once on the same translation unit, but it can still be included by another translation unit.
I managed to make your project run with Ceedling 1.0.0 by doing the following:
- Modify `test/test/support/bgm220pc22wga.h` to declare `TIMER0` always extern.
e.g:

```c
#ifndef BGM220PC22WGA_H
#define BGM220PC22WGA_H

#include "micro_registers.h"

#include "core_cm33.h"    /* Core Header File */
#include "bgm22_timer.h"

// NOTE: This is the definition of TIMER0, which in the SDK uses a particular address. This won't work when testing, as
// we don't know what's stored in that address in the computer...
// #define TIMER0_NS_BASE               (0x50048000UL) /* TIMER0_NS base address */
// #define TIMER0_BASE               (TIMER0_NS_BASE)           /* TIMER0 base address */
// #define TIMER0                  ((TIMER_TypeDef *) TIMER0_BASE)                           /**< TIMER0 base pointer */
extern TIMER_TypeDef TIMER0;


#endif // BGM220PC22WGA_H
```

- Create file `test/test/support/bgm220pc22wga.c` that includes the header file above and with the `TIMER0` definition. I don't know why are defining it as a pointer, in that case it should be initialized, instead I chose to define it as a `TIMER_TypeDef` struct type.
e.g.:
```c
#include "bgm220pc22wga.h"

TIMER_TypeDef TIMER0;
```

- Modify `src/src/a.c` to access `TIMER0` as a struct instead of an struct pointer.
e.g.:
```c
#include "a.h"

#include "em_timer.h"

void foo(void) {
    TIMER0.EN_SET = TIMER_EN_EN;
}
```

- In my case, the compiler complains about missing include file `stdint.h` in `bgm22_timer.h` so I added `#include <stdint.h>` to it.

And regarding whether there is a bug on Ceedling, I found this [issue](https://github.com/ThrowTheSwitch/Ceedling/issues/621). It seems that previously, the generated test runner source files didn't include the same header files as the test source. But now, all test runners include the header files from their respective test source, as you are including `em_device.h` in `test_a.c`, that same header file is included in the generated test runner `test_a_runner.c`, so effectively `TIMER0`is now defined in two separate translation units.

**Comment by mundodisco8** [comment]
> The include guard will only avoid for the same header file to be included more than once on the same translation unit, but it can still be included by another translation unit.
The use of a second header (in my case `testable_micro_registers.h`) prevents `TIMER0` from being defined more than once. This is because I control when to add `testable_micro_registers.h`, and by adding it only to `test_a.c`, I know it's only included in one translation unit, and thus, only defined once.
I think you hit the nail in the head with the issue you linked. I think the problem is that to cover a very specific test case they prevented another very specific test case to work 😆 

>[...] the TIMER0 definition. I don't know why are defining it as a pointer, in that case it should be initialized,
TIMER0 is a register in a microcontroller. I don't know how much you know about embedded development, so excuse me if you know this already, but in the "real" code, TIMER0 points to a position in memory in the microcontroller. By mapping registers to memory space, you can read and write on them as if they were RAM. TIMER0 points to a position in memory I can't access in my computer, where I run the tests, as you don't know what's on it in the target computer (even if it's accessible at all!).

The trick I'm trying to use is to keep TIMER0 defined as a pointer, so all the code works all the same, but then doing a switcheroo and provide some memory for a "fake register", and then make TIMER0 point to my "fake register".

Again, thanks for your help and spending so much time on this

**Comment by mundodisco8** [comment]
Hi,

I noticed this was closed, but I can't get it to work in Ceedling v1.0. Does it mean that this approach to get registers in unit tests is not recommended?

As a breif summary of my issue, the problem seems to be in the fact that now, test_NAME_runner.c #includes the same #includes as the test file and that creates two copies of my "fake register". If there's no plan to change that, then I'll remove my tests and carry on.

**Comment by deltalejo** [comment]
My recommendation is to declare your registers as `extern` on the header file and define them in a source file instead on relying on preprocessor tricks. This is basically the approach I take for unit testing with registers and that has worked for me across different microcontrollers and Ceedling versions.
This is what I usually do:
- Copy the microcontroller header file provided by the vendor/toolchain to the project. I place it under `test/support` dir.
- Strip any toolchain specific stuff for the header file, e.g.: double underscore keywords or attributes to place the registers at specific address.
- Add `extern` to each register declaration in case they aren't declared this way originally.
- Add a companion source file for the header file above with registers definitions, i.e. without `extern` keyword.
- Tell Ceedling to compile that file for your tests.

**Comment by Letme** [comment]
I also do the same as @deltalejo :

```
extern volatile GPIO_Type gpio_base;
#define GPIO_BASE                               (&gpio_base))
```

Then in test file you just do:

```
volatile GPIO_Type gpio_base;
```

And you have all control that you want over read/write of the register and address while using the whole library of the vendor (so you actually also test all their shifts and stuff).
