### ISSUE TITLE
Ceedling cannot find the mock header file during the compilation of the _runner.c

### ISSUE THREAD

**Issue by anoshyn** [ThrowTheSwitch/Ceedling#941]
The `Xxx_Xxxxxxx_Xxxxx_V1.44` header file isn't correctly included in the list of files that Ceedling needs to mock.  My header file is named `Xxx_Xxxxxxx_Xxxxx_V1.44.h`, the mock file should be `mock_Xxx_Xxxxxx_Xxxxx_V1.44.h`. However, in the runner, it looks for `mock_Xxx_Xxxxxxx_Xxxxx_V1.h`. I am working with legacy code, so it would be very difficult to adjust the file names to ensure consistency to handle this correctly. Can I change Ceedling configuration to handle this correctly through its mock configuration settings?

```
Generating runner for test_XxxxxxxXxxxXxxxxxx.c...
Compiling test_XxxxxxxXxxxXxxxxxx_runner.c...
build/test/runners/test_XxxxxxxXxxxXxxxxxx_runner.c:10:39: fatal error: mock_Xxx_Xxxxxxx_Xxxxx_V1.h: No such file or directory
 #include "mock_Xxx_Xxxxxxx_Xxxxx_V1.h"
                                       ^
compilation terminated.
```

**Comment by Letme** [comment]
So someone is doing manual version control of the header files and (important) uses dot as separator, and now you want to configure a general usage tool for this bad practice? I would sure like to know which developers and library is that, so that I can stear clear.

Just a useless rant, but I do not think there is a configuration fix as Ceedling already uses .h for file-endings and if it cuts after first dot then its what you would consider a bug in parsing. Further more, this is part of CMock most likely.

**Comment by anoshyn** [comment]
You're absolutely right — having version numbers with dots in header file names can complicate things, especially when using tools like Ceedling and CMock. This is less about Ceedling's configuration flexibility and more about CMock's parsing limitations. If it encounters a dot and interprets it as a file extension delimiter, it could cause exactly the kind of issue I'm facing. Maybe you have some few suggestions that could help mitigate or work around this problem?

**Comment by mkarlesky** [comment]
@anoshyn, What an interesting quirk in legacy file naming! I'll cut to the chase… This is now fixed in the upcoming 1.0.0 Ceedling release. The fix will be available in a new prerelease build soon.

Long story short, Ceedling juggles file extensions all over the place. Certain utility methods are quite handy for removing, changing, or adding file extensions to filenames. Ceedling makes assumptions throughout that filenames have a base name and then only a dotted filename extension. In a few key places, that assumption falls apart in cases like yours because of the utility methods I mention. In certain places those utility methods were used in brute force ways among filename slicing and dicing that gobbled up and replaced the dotted portion of the filename as you experienced. It may be bad practice to include dotted version numbers as already noted, but having multiple periods in filenames is legal. So, we should do our best to support this.
